export const PRODUCTS = [
  {
    id: "1",
    title: "Programming Pearls, 2nd edition",
    author: "Jon Bentley",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "2",
    title: "Clean Code Series by Robert Martin",
    author: "Robert C. Martin",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "3",
    title: "The Art of Computer Programming",
    author: "Donald Knuth",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "4",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "5",
    title: "New Programmer’s Survival Manual",
    author: "Josh Carter",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "6",
    title: "Grokking Algorithms",
    author: "Aditya Y. Bhargava",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "7",
    title: "The Pragmatic Programmer: 20th Anniversary Edition, 2nd Edition",
    author: "Thomas David, Hunt Andrew",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "8",
    title: "Head First Design Patterns",
    author: "Elisabeth Freeman, Eric Freeman, Bert Bates, Kathy Sierra",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "9",
    title: "Ruby. Object-oriented design",
    author: "Sandy Metz",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "10",
    title: "Code Complete",
    author: "Steve McConnell",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "11",
    title: "Functional Programming in C#",
    author: "Oliver Sturm",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "12",
    title:
      "Effective C++: 55 Specific Ways to Improve Your Programs and Designs",
    author: "Steve Meyers",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "13",
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "14",
    title: "TypeScript Deep Dive",
    author: "Basarat Ali Syed",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "15",
    title: "Python. Test-Based Development",
    author: "Harry Percival",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "16",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "17",
    title: "If Hemingway Wrote Javascript",
    author: "Angus Croll",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "18",
    title: "The Mythical Man-month",
    author: "Frederick Brooks",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "19",
    title: "Laws of Simplicity",
    author: "John Maeda",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
  {
    id: "20",
    title: "Coders at Work: Reflections on the Craft of Programming",
    author: "Peter Seibel",
    price: 5,
    count: 10,
    description: "The best book ever!",
  },
];
